config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #
  # get "0000" => "calamities#index"
  root "calamities#index"
  resources :calamities, path_names: {new: "0000", edit: "1111"} do
    resources :comments, except: :show
  end
  resources :categories
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city_municipality, optional: true
  belongs_to :district, optional: true
  belongs_to :province, optional: true
end

app/models/address/city_municipality.rb
class Address::CityMunicipality < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region, optional: true
  belongs_to :district, optional: true
  belongs_to :province, optional: true
  has_many :barangays
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region

end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  has_many :city_municipalities
  has_many :provinces
  has_many :districts
  # has_many :calamities, class_name: 'Calamity', foreign_key: 'address_region_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calamity.rb
class Calamity < ApplicationRecord
  # default_scope { where(delete_at: nil) }
  validates :title, presence: :true
  validates :content, presence: :true
  validates :address, presence: :true
  
  belongs_to :user
  has_many :comments
  has_many :calamity_category_ships
  has_many :categories, through: :calamity_category_ships
  # def destroy
  #   update(delete_at: Time.now)
  # end
end

app/models/calamity_category_ship.rb
class CalamityCategoryShip < ApplicationRecord
  belongs_to :calamity
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :calamity_category_ships
  has_many :calamities, through: :calamity_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :calamity, counter_cache: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :calamities
  has_many :comments
end

app/controllers/api/regions_controller.rb
class Api::RegionsController < ApplicationController
  def index
    regions = Address::Region.all
    render json: regions, each_serializer: RegionSerializer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calamities_controller.rb
class CalamitiesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  # before_action :set_categories, [:index, :edit, :update, :create]
  before_action :set_calamity, only: [:show, :update, :edit, :destroy]

  # before_action only: [:new, :create, :show, :destroy, :edit, :update]
  # before_action :set_categories, only: :update

  def index
    @calamities = Calamity.includes(:categories, :user).page(params[:page]).per(5)
  end

  def new
    @calamity = Calamity.new
  end

  def show
    @calamity = Calamity.find(params[:id])
  end

  def create
    @calamity = Calamity.new(params[:calamity].permit(:title, :content, :address, category_ids: []))
    @calamity = Calamity.new(params[:calamity].permit(:title, :content, :address, :unique_id, category_ids: []))
    @calamity.user = current_user
    if Rails.env.development?
      @calamity.ip_address = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    else
      @calamity.ip_address = request.remote_ip
    end
    if @calamity.save
      redirect_to calamities_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @calamity.user = current_user
    if @calamity.update(set_categories)
      redirect_to calamities_path
    else
      render :edit
    end
  end

  def destroy
    @calamity = Calamity.find(params[:id])
    @calamity.destroy
    redirect_to calamities_path
  end

  # def validate_post_owner
  #   unless @calamity.user == current_user
  #     flash[:notice] = 'the post not belongs to you'
  #     redirect_to calamities_path
  #   end
  # end

  def set_categories
    params.require(:calamity).permit(:title, :content, :address, category_ids: [])
  end

  def set_calamity
    @calamity = Calamity.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end
  #
  # def set_category
  #   @category = Category.find(params[:id])
  # end

  def params_category
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Calamity.includes(:user).page(params[:page]).per(5)
  end

  def new
    @comment = @calamity.comments.build
  end

  def create
    @comment = @calamity.comments.build(params_comment)
    @comment.user = current_user
    if @comment.save
      redirect_to calamities_path(params[:calamity_id])
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(content: params[:comment][:content])
      redirect_to calamities_path(@calamity)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to calamity_path(params[:calamity_id])
  end

  private

  def set_comment
    @comment = @calamity.comments.find(params[:id])
  end

  def set_post
    @calamity = Calamity.find(params[:calamity_id])
  end

  def params_comment
    params.require(:comment).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # before_action :set_post, only: [:new, :create, :edit, :update]
  #
  # def index
  #   @calamities = Calamity.includes(:user).all
  # end
  #
  # def new
  #   @calamity = Calamity.new
  # end
  #
  # def create
  #   @calamity = Calamity.find(set_post)
  #   @calamity.save
  #   render :new
  # end
  #
  # def edit; end
  #
  # def update
  #   @calamity = Calamity.find(params[:id].permit(:title, :content))
  #   @calamity.update(params[:id])
  #   render :edit
  #
  # end
  #
  # def set_post
  #   @calamity = Calamity.find(params[:post_id].permit(:title, :content))
  # end
end

app/helpers/api/barangays_helper.rb
module Api::BarangaysHelper
end

app/helpers/api/regions_helper.rb
module Api::RegionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calamities_helper.rb
module CalamitiesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calamities/_form.html.erb
<header><%= current_user.email %></header>
<%= form_with model: @calamity do |form| %>
  <% if @calamity.errors.any? %>
    <ul>
      <% @calamity.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <%= form.submit %>
<% end %>

app/views/calamities/edit.html.erb
<%= current_user.email %><h1>Edit Post</h1>
<% if @calamity.errors.any? %>
  <ul>
    <% @calamity.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @calamity do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <%=  form.submit 'Update' %>
<% end %>

app/views/calamities/index.html.erb
<!--<body class="text-hide" style="background-image: url('../images/disaster.jpeg'); width: 50px; height: 50px; ">-->


<h1>Post List </h1>

<table class="table table-striped table-bordered">

  <thead style="background: #badbcc; font-weight: bold; text-align: center">
  <td>Id</td>
  <td>Title</td>
  <td>Address</td>
  <td>Content</td>
  <td>Categories</td>
  <td>Comments Count</td>
  <td>IP Address</td>
  <td>User</td>
  <td>Action</td>
  </thead>
  <% @calamities.each do |calamity| %>
    <div class="w3-container w3-teal ">
      <tr>
        <td><%= calamity.id %></td>
        <td><%= calamity.title %></td>
        <td><%= calamity.address %></td>
        <td><%= calamity.content %></td>
        <td><%= calamity.categories.pluck(:name).join(',') %></td>
        <td><%= calamity.comments_count  %></td>
        <td><%= calamity.user.current_sign_in_ip %></td>
        <td><%= calamity.user.email %></td>
        <td style="display: flex"><%= link_to 'Edit', edit_calamity_path(calamity), class: "btn btn-secondary" if calamity.user == current_user %>
          <%= link_to 'Show', calamity_path(calamity), class: "btn btn-primary" %>
          <%= button_to 'Delete', calamity_path(calamity), class: "btn btn-danger ", method: :delete if calamity.user == current_user %></td>
  <% end %>
  </div>
  </tr>
</table>
<%= paginate @calamities %>
<%= link_to 'New', new_calamity_path(@calamity), class: "btn btn-primary" %>
<!--</body>-->

app/views/calamities/new.html.erb
<%= current_user.email %>
<header style="float: left"><%= link_to "Home Page", calamities_path, class: "btn btn-secondary" %></header>

<h1>New Post</h1>
<% if @calamity.errors.any? %>
  <ul>
    <% @calamity.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @calamity, data: { controller: :location } do |form| %>
  <div class="w3-container w3-center">
    <div class="form">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <!--    <div class="form">-->
    <%#= form.label :address %>
    <%#= form.text_field :address %>
    <!--    </div>-->

    <div class="form">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>

    <div>
      <%= form.label :unique_id %>
      <%= form.text_field :unique_id, value: @rand %>
    </div>


    <div>
      <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
    </div>
    <div>
      <%= form.label :address_region_id %>
      <%= form.collection_select :address_region_id,
                                 Address::Region.all, :id, :name,
                                 { prompt: 'PLEASE SELECT REGION' },
                                 data: { location_target: 'selectedRegionId', action: 'change->location#fetchProvinces' } %>
    </div>

    <div>
      <%= form.label :address_province_id %>
      <%= form.collection_select :address_province_id, [], nil, nil, { prompt: 'PLEASE SELECT PROVINCE' }, data: { location_target: 'selectProvinceId', action: 'change->location#fetchCitiesMunicipalities' } %>
    </div>

    <div>
      <%= form.label :address_city_municipality_id %>
      <%= form.collection_select :address_city_municipality_id, [], nil, nil, { prompt: 'PLEASE SELECT MUNICIPALITY' }, data: { location_target: 'selectCityMunicipalityId' } %>
    </div>

    <div>
      <%= form.label :address_city_municipality_id %>
      <%= form.collection_select :address_city_municipality_id, [], nil, nil, { prompt: 'PLEASE SELECT MUNICIPALITY' }, data: { location_target: 'selectCityMunicipalityId' } %>
    </div>

    <div>
      <%= form.file_field :image %>
    </div>
    <div class="btn-light">
      <%= form.submit 'Save', class: "btn btn-primary" %>
    </div>
    <%= link_to "Add Categories", categories_path, class: "btn btn-primary" %>


<% end %>
</div>

app/views/calamities/show.html.erb
<%= current_user.email %>

<h1>show post id: <%= @calamity.id %></h1>
<table class="table table-bordered">
  <thead>
  <td>Id</td>
  <td>Title</td>
  <td>Content</td>
  <td>Comment</td>
  </thead>
  <tr>
    <td><%= @calamity.id %></td>
    <td><%= @calamity.title %></td>
    <td><%= @calamity.content %></td>
    <td>
      <% @calamity.comments.each do |comment| %>
        <ul style="display: flex">
          <%= comment.content %>
          <%= link_to 'Edit', edit_calamity_comment_path(@calamity, comment), class: "btn btn-secondary" %>
        <%= button_to 'Delete', calamity_path(@calamity), method: :delete, class: "btn btn-danger" %></ul>
      <% end %>
    </td>
  </tr>
  <br>
</table>
<%= link_to 'Home', calamities_path, class:"btn btn-primary bi bi-arrow-return-left"%>
<%= link_to 'Add Comment', new_calamity_comment_path(@calamity), class: "btn btn-warning" %>

app/views/categories/_form.html.erb
<%= form_with model: categories, url: categories_path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/index.html.erb
<% @categories.each do |calamity| %>
  <%= calamity.name %>
<% end %>

<%= link_to "Add Category", new_category_path, class: "btn btn-primary" %>
<%= link_to "Home", calamities_path, class: "btn btn-secondary" %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: calamity_comments_path, data: { turbo: false } do |form| %>
  <% if @comment.errors.any? %>
    <ul>
      <% @comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit 'Save'%>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%=  @calamity.title %></h1>
<h2>Edit comment id: <%= @comment.calamity_id %></h2>
<%= render partial: 'form', locals: {calamity: @calamity, comment: @comment,  path: calamity_comment_path(@calamity, @comment)} %>

app/views/comments/index.html.erb
<h1>Title<%= @calamity.content%></h1>
<h2>Comments</h2>

<% @calamity.comments.each do |f|%>
  <ul>
    <%= f.content %>
  </ul>
<% end %>

<%#= link_to 'Show', calamity_comment_path(@calamity)%>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render partial: 'form', locals: {post: @calamity, comment: @comment, path: calamity_comments_path} %>